name: Deploy to Shared Hosting

on:
  push:
    branches:
      - refactor # Change this to the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Change this to your PHP version

      - name: Debugging
        run: pwd

      - name: Debugging
        run: cd ./vpl

      - name: Debugging
        run: ls
